¿OKR: Proposito?

Exploración de datos: (EDA)
1. Revisar estructura, tamaño, los tipos de datos
2. detectar, identificar nulos, cardinalidades, duplicados
3. Analizar las variables categóricas y númericas
4. detectar formatos de fechas no están estandarizados, homogeneidad
5. outliers o datos atipicos
6. tipografía (formato, todo se maneja upper, lower)
7. perfil de la calidad del dato
8. generar reportes de ese eda, gráficas, histo, tablas

In [1]:
# ANALISIS DE ARCHIVO CON COLUMNAS RENOMBRADAS
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import yaml
from pathlib import Path

ROOT = Path.cwd().resolve()
if not (ROOT / "config" / "config.yaml").is_file():
    ROOT = ROOT.parent
config_path = ROOT / "config" / "config.yaml"
if not config_path.is_file():
    raise FileNotFoundError("No se encontro config/config.yaml desde la carpeta actual.")
with config_path.open("r", encoding="utf-8") as file:
    config = yaml.safe_load(file)
bronze_dir = ROOT / config["paths"]["bronze_dir"]

caracteristicas_generales = pd.read_csv(
    bronze_dir / config["source"]["csv_salida_cg"], low_memory=False
)
print("Caracteristicas generales")
display(caracteristicas_generales.head(20))
display(caracteristicas_generales.shape)
display(caracteristicas_generales.info())
display(caracteristicas_generales.describe())

Caracteristicas generales

,Unnamed: 0,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Tipo_Registro,Area_Metropolitana,...,Asiste_Institucion_Educativa,Tipo_Institucion_Educativa,Nivel_Educativo,Grado_Aprobado,Area_Nivel_Educativo,Titulo_o_Diploma,Titulo_Diploma_EnQue,Atraccion_Sexual_Romantica,Identidad_Autorreconocida,Poblacion_Mayor_18
0,0,20251252,12,2025,8435963,1,1,1,10,NaN,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
1,1,20251252,12,2025,8435963,1,2,1,10,NaN,...,2.0,NaN,8.0,4.0,419.0,5.0,419.0,1.0,2.0,1.0
2,2,20251252,12,2025,8435963,1,3,1,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,20251252,12,2025,8435964,1,1,1,10,NaN,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
4,4,20251252,12,2025,8435965,1,1,1,10,NaN,...,2.0,NaN,3.0,5.0,NaN,NaN,NaN,2.0,1.0,1.0
5,5,20251252,12,2025,8435966,1,1,1,10,NaN,...,2.0,NaN,3.0,5.0,NaN,NaN,NaN,2.0,1.0,1.0
6,6,20251252,12,2025,8435967,1,1,1,10,NaN,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
7,7,20251252,12,2025,8435968,1,1,1,10,NaN,...,2.0,NaN,4.0,1.0,NaN,NaN,NaN,2.0,1.0,1.0
8,8,20251252,12,2025,8435969,1,1,1,10,NaN,...,2.0,NaN,8.0,3.0,731.0,5.0,731.0,1.0,2.0,1.0
9,9,20251252,12,2025,8435970,1,1,1,10,NaN,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
10,10,20251252,12,2025,8435970,1,2,1,10,NaN,...,2.0,NaN,10.0,10.0,411.0,7.0,411.0,1.0,2.0,1.0
11,11,20251252,12,2025,8435970,1,3,1,10,NaN,...,1.0,1.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
12,12,20251252,12,2025,8435970,1,4,1,10,NaN,...,1.0,1.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
13,13,20251252,12,2025,8435971,1,1,1,10,NaN,...,2.0,NaN,3.0,4.0,NaN,NaN,NaN,2.0,1.0,1.0
14,14,20251252,12,2025,8435972,1,1,1,10,NaN,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
15,15,20251252,12,2025,8435973,1,1,1,10,NaN,...,2.0,NaN,3.0,5.0,NaN,NaN,NaN,1.0,2.0,1.0
16,16,20251252,12,2025,8435973,1,2,1,10,NaN,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
17,17,20251252,12,2025,8435974,1,1,1,10,NaN,...,2.0,NaN,5.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0
18,18,20251252,12,2025,8435974,1,2,1,10,NaN,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
19,19,20251252,12,2025,8435975,1,1,1,10,NaN,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0

(203851, 56)

<class 'pandas.DataFrame'>
RangeIndex: 203851 entries, 0 to 203850
Data columns (total 56 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Unnamed: 0                    203851 non-null  int64
 1   Periodo_Recoleccion           203851 non-null  int64
 2   Mes_Encuesta                  203851 non-null  int64
 3   Anio_Encuesta                 203851 non-null  int64
 4   Id_Vivienda                   203851 non-null  int64
 5   Id_Hogar                      203851 non-null  int64
 6   Orden_Persona                 203851 non-null  int64
 7   Numero_Hogar                  203851 non-null  int64
 8   Tipo_Registro                 203851 non-null  int64
 9   Area_Metropolitana            147817 non-null  float64
 10  Clase_Dominio                 203851 non-null  int64
 11  Factor_Expansion              203851 non-null  float64
 12  Departamento                  203851 non-null  int64
 13  Poblacion_Total               203851 non-null  int64
 14  Orden_Informante              203851 non-null  int64
 15  Sexo_Al_Nacer                 203851 non-null  int64
 16  Edad                          203851 non-null  int64
 17  Mes_Nacimiento                202908 non-null  float64
 18  Anio_Nacimiento               202908 non-null  float64
 19  Parentesco_Jefe_Hogar         203851 non-null  int64
 20  Madre_Reside_Hogar            203851 non-null  int64
 21  Orden_Madre                   75783 non-null   float64
 22  Padre_Reside_Hogar            203851 non-null  int64
 23  Orden_Padre                   39344 non-null   float64
 24  Se_Considera_Campesino        203851 non-null  int64
 25  Fue_Campesino                 141926 non-null  float64
 26  Comunidad_Campesina           203851 non-null  int64
 27  Autorreconocimiento_Etnico    203851 non-null  int64
 28  Pueblo_Indigena               9358 non-null    str
 29  Otro_Pueblo_Indigena          0 non-null       float64
 30  Estado_Conyugal               179277 non-null  float64
 31  Conyuge_Reside_Hogar          78577 non-null   float64
 32  Orden_Conyuge                 74382 non-null   float64
 33  Afiliacion_Salud              203851 non-null  int64
 34  Regimen_Salud                 197639 non-null  float64
 35  Quien_Paga_Salud              89294 non-null   float64
 36  Pago_Mensual_Salud            52289 non-null   float64
 37  Dificultad_Oir                203851 non-null  int64
 38  Dificultad_Hablar             203851 non-null  int64
 39  Dificultad_Ver                203851 non-null  int64
 40  Dificultad_Movilidad          203851 non-null  int64
 41  Dificultad_Manipular_Objetos  203851 non-null  int64
 42  Dificultad_Cognitiva          203851 non-null  int64
 43  Dificultad_Autocuidado        203851 non-null  int64
 44  Dificultad_Interaccion        203851 non-null  int64
 45  Sabe_Leer_Escribir            198320 non-null  float64
 46  Asiste_Institucion_Educativa  198320 non-null  float64
 47  Tipo_Institucion_Educativa    51506 non-null   float64
 48  Nivel_Educativo               198320 non-null  float64
 49  Grado_Aprobado                198320 non-null  float64
 50  Area_Nivel_Educativo          50500 non-null   float64
 51  Titulo_o_Diploma              104226 non-null  float64
 52  Titulo_Diploma_EnQue          39448 non-null   float64
 53  Atraccion_Sexual_Romantica    153766 non-null  float64
 54  Identidad_Autorreconocida     153766 non-null  float64
 55  Poblacion_Mayor_18            153766 non-null  float64
dtypes: float64(25), int64(30), str(1)
memory usage: 87.1 MB

None

,Unnamed: 0,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Tipo_Registro,Area_Metropolitana,...,Asiste_Institucion_Educativa,Tipo_Institucion_Educativa,Nivel_Educativo,Grado_Aprobado,Area_Nivel_Educativo,Titulo_o_Diploma,Titulo_Diploma_EnQue,Atraccion_Sexual_Romantica,Identidad_Autorreconocida,Poblacion_Mayor_18
count,203851.000000,2.038510e+05,203851.000000,203851.0,2.038510e+05,203851.000000,203851.000000,203851.000000,203851.0,147817.000000,...,198320.000000,51506.000000,198320.000000,198320.000000,50500.000000,104226.000000,39448.000000,153766.000000,153766.000000,153766.0
mean,33981.808905,2.025115e+07,10.989448,2025.0,8.420545e+06,1.005936,2.283428,1.005936,10.0,41.525332,...,1.740288,1.201588,5.255577,3.198039,537.310475,3.680819,536.301714,1.463614,1.548327,1.0
std,19627.901852,8.488126e+01,0.814530,0.0,2.848047e+04,0.089826,1.386471,0.089826,0.0,26.685148,...,0.438477,0.401190,2.786131,2.617025,281.214598,2.317828,283.337758,0.519761,0.499526,0.0
min,0.000000,2.025104e+07,10.000000,2025.0,8.374095e+06,1.000000,1.000000,1.000000,10.0,5.000000,...,1.000000,1.000000,1.000000,0.000000,11.000000,1.000000,11.000000,1.000000,1.000000,1.0
25%,16987.000000,2.025104e+07,10.000000,2025.0,8.395412e+06,1.000000,1.000000,1.000000,10.0,17.000000,...,1.000000,1.000000,3.000000,2.000000,411.000000,2.000000,411.000000,1.000000,1.000000,1.0
50%,33975.000000,2.025115e+07,11.000000,2025.0,8.420196e+06,1.000000,2.000000,1.000000,10.0,44.000000,...,2.000000,1.000000,5.000000,2.000000,421.000000,2.000000,421.000000,1.000000,2.000000,1.0
75%,50962.000000,2.025125e+07,12.000000,2025.0,8.442654e+06,1.000000,3.000000,1.000000,10.0,66.000000,...,2.000000,1.000000,8.000000,4.000000,729.000000,6.000000,731.000000,2.000000,2.000000,1.0
max,68709.000000,2.025125e+07,12.000000,2025.0,8.473908e+06,5.000000,16.000000,5.000000,10.0,99.000000,...,2.000000,2.000000,99.000000,99.000000,2198.000000,99.000000,2198.000000,4.000000,4.000000,1.0

In [2]:
# ANALISIS EXPLORATORIO DE DATOS SIN RENOMBRAR COLUMNAS
caracteristicas_generales = pd.read_csv(
    bronze_dir / config["source"]["csv_salida_cg_sinrenombrar"], low_memory=False
)
print("Caracteristicas generales sin renombrar")
display(caracteristicas_generales.head(20))
display(caracteristicas_generales.shape)
display(caracteristicas_generales.info())
display(caracteristicas_generales.describe())

Caracteristicas generales sin renombrar

,Unnamed: 0,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,...,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,0,20251252,12,2025,8435963,1,1,1,10,NaN,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
1,1,20251252,12,2025,8435963,1,2,1,10,NaN,...,2.0,NaN,8.0,4.0,419.0,5.0,419.0,1.0,2.0,1.0
2,2,20251252,12,2025,8435963,1,3,1,10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,20251252,12,2025,8435964,1,1,1,10,NaN,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
4,4,20251252,12,2025,8435965,1,1,1,10,NaN,...,2.0,NaN,3.0,5.0,NaN,NaN,NaN,2.0,1.0,1.0
5,5,20251252,12,2025,8435966,1,1,1,10,NaN,...,2.0,NaN,3.0,5.0,NaN,NaN,NaN,2.0,1.0,1.0
6,6,20251252,12,2025,8435967,1,1,1,10,NaN,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
7,7,20251252,12,2025,8435968,1,1,1,10,NaN,...,2.0,NaN,4.0,1.0,NaN,NaN,NaN,2.0,1.0,1.0
8,8,20251252,12,2025,8435969,1,1,1,10,NaN,...,2.0,NaN,8.0,3.0,731.0,5.0,731.0,1.0,2.0,1.0
9,9,20251252,12,2025,8435970,1,1,1,10,NaN,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
10,10,20251252,12,2025,8435970,1,2,1,10,NaN,...,2.0,NaN,10.0,10.0,411.0,7.0,411.0,1.0,2.0,1.0
11,11,20251252,12,2025,8435970,1,3,1,10,NaN,...,1.0,1.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
12,12,20251252,12,2025,8435970,1,4,1,10,NaN,...,1.0,1.0,4.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
13,13,20251252,12,2025,8435971,1,1,1,10,NaN,...,2.0,NaN,3.0,4.0,NaN,NaN,NaN,2.0,1.0,1.0
14,14,20251252,12,2025,8435972,1,1,1,10,NaN,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
15,15,20251252,12,2025,8435973,1,1,1,10,NaN,...,2.0,NaN,3.0,5.0,NaN,NaN,NaN,1.0,2.0,1.0
16,16,20251252,12,2025,8435973,1,2,1,10,NaN,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
17,17,20251252,12,2025,8435974,1,1,1,10,NaN,...,2.0,NaN,5.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0
18,18,20251252,12,2025,8435974,1,2,1,10,NaN,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
19,19,20251252,12,2025,8435975,1,1,1,10,NaN,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0

(203851, 56)

<class 'pandas.DataFrame'>
RangeIndex: 203851 entries, 0 to 203850
Data columns (total 56 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   203851 non-null  int64
 1   PERIODO      203851 non-null  int64
 2   MES          203851 non-null  int64
 3   PER          203851 non-null  int64
 4   DIRECTORIO   203851 non-null  int64
 5   SECUENCIA_P  203851 non-null  int64
 6   ORDEN        203851 non-null  int64
 7   HOGAR        203851 non-null  int64
 8   REGIS        203851 non-null  int64
 9   AREA         147817 non-null  float64
 10  CLASE        203851 non-null  int64
 11  FEX_C18      203851 non-null  float64
 12  DPTO         203851 non-null  int64
 13  PT           203851 non-null  int64
 14  P6016        203851 non-null  int64
 15  P3271        203851 non-null  int64
 16  P6040        203851 non-null  int64
 17  P6030S1      202908 non-null  float64
 18  P6030S3      202908 non-null  float64
 19  P6050        203851 non-null  int64
 20  P6083        203851 non-null  int64
 21  P6083S1      75783 non-null   float64
 22  P6081        203851 non-null  int64
 23  P6081S1      39344 non-null   float64
 24  P2057        203851 non-null  int64
 25  P2059        141926 non-null  float64
 26  P2061        203851 non-null  int64
 27  P6080        203851 non-null  int64
 28  P6080S1      9358 non-null    str
 29  P6080S1A1    0 non-null       float64
 30  P6070        179277 non-null  float64
 31  P6071        78577 non-null   float64
 32  P6071S1      74382 non-null   float64
 33  P6090        203851 non-null  int64
 34  P6100        197639 non-null  float64
 35  P6110        89294 non-null   float64
 36  P6120        52289 non-null   float64
 37  P1906S1      203851 non-null  int64
 38  P1906S2      203851 non-null  int64
 39  P1906S3      203851 non-null  int64
 40  P1906S4      203851 non-null  int64
 41  P1906S5      203851 non-null  int64
 42  P1906S6      203851 non-null  int64
 43  P1906S7      203851 non-null  int64
 44  P1906S8      203851 non-null  int64
 45  P6160        198320 non-null  float64
 46  P6170        198320 non-null  float64
 47  P3041        51506 non-null   float64
 48  P3042        198320 non-null  float64
 49  P3042S1      198320 non-null  float64
 50  P3042S2      50500 non-null   float64
 51  P3043        104226 non-null  float64
 52  P3043S1      39448 non-null   float64
 53  P3038        153766 non-null  float64
 54  P3039        153766 non-null  float64
 55  POB_MAY18    153766 non-null  float64
dtypes: float64(25), int64(30), str(1)
memory usage: 87.1 MB

None

,Unnamed: 0,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,...,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
count,203851.000000,2.038510e+05,203851.000000,203851.0,2.038510e+05,203851.000000,203851.000000,203851.000000,203851.0,147817.000000,...,198320.000000,51506.000000,198320.000000,198320.000000,50500.000000,104226.000000,39448.000000,153766.000000,153766.000000,153766.0
mean,33981.808905,2.025115e+07,10.989448,2025.0,8.420545e+06,1.005936,2.283428,1.005936,10.0,41.525332,...,1.740288,1.201588,5.255577,3.198039,537.310475,3.680819,536.301714,1.463614,1.548327,1.0
std,19627.901852,8.488126e+01,0.814530,0.0,2.848047e+04,0.089826,1.386471,0.089826,0.0,26.685148,...,0.438477,0.401190,2.786131,2.617025,281.214598,2.317828,283.337758,0.519761,0.499526,0.0
min,0.000000,2.025104e+07,10.000000,2025.0,8.374095e+06,1.000000,1.000000,1.000000,10.0,5.000000,...,1.000000,1.000000,1.000000,0.000000,11.000000,1.000000,11.000000,1.000000,1.000000,1.0
25%,16987.000000,2.025104e+07,10.000000,2025.0,8.395412e+06,1.000000,1.000000,1.000000,10.0,17.000000,...,1.000000,1.000000,3.000000,2.000000,411.000000,2.000000,411.000000,1.000000,1.000000,1.0
50%,33975.000000,2.025115e+07,11.000000,2025.0,8.420196e+06,1.000000,2.000000,1.000000,10.0,44.000000,...,2.000000,1.000000,5.000000,2.000000,421.000000,2.000000,421.000000,1.000000,2.000000,1.0
75%,50962.000000,2.025125e+07,12.000000,2025.0,8.442654e+06,1.000000,3.000000,1.000000,10.0,66.000000,...,2.000000,1.000000,8.000000,4.000000,729.000000,6.000000,731.000000,2.000000,2.000000,1.0
max,68709.000000,2.025125e+07,12.000000,2025.0,8.473908e+06,5.000000,16.000000,5.000000,10.0,99.000000,...,2.000000,2.000000,99.000000,99.000000,2198.000000,99.000000,2198.000000,4.000000,4.000000,1.0

In [3]:
# ANALISIS EXPLORATORIO DE OCUPADOS SIN RENOMBRAR COLUMNAS
ocupados = pd.read_csv(
    bronze_dir / config["source"]["csv_salida_ocupados_sinrenombrar"], low_memory=False
)
display(ocupados.head(20))
display(ocupados.shape)
display(ocupados.info())
display(ocupados.describe())

,Unnamed: 0,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,...,P1881,P1881S1,P1882,P7240,P7240S1,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
0,0,20251252,12,2025,8435963,1,1,1,60,NaN,...,9,NaN,5.0,8,NaN,1,1200000.0,3,311,6223
1,1,20251252,12,2025,8435963,1,2,1,60,NaN,...,11,NaN,20.0,3,NaN,1,NaN,56,5611,9412
2,2,20251252,12,2025,8435964,1,1,1,60,NaN,...,9,NaN,30.0,3,NaN,1,2000000.0,3,311,6222
3,3,20251252,12,2025,8435965,1,1,1,60,NaN,...,9,NaN,25.0,3,NaN,1,1800000.0,3,311,6222
4,4,20251252,12,2025,8435966,1,1,1,60,NaN,...,9,NaN,20.0,3,NaN,1,2400000.0,3,311,6222
5,5,20251252,12,2025,8435967,1,1,1,60,NaN,...,9,NaN,30.0,9,NaN,1,1500000.0,3,311,6223
6,6,20251252,12,2025,8435968,1,1,1,60,NaN,...,9,NaN,25.0,3,NaN,1,1650000.0,3,311,6222
7,7,20251252,12,2025,8435969,1,1,1,60,NaN,...,3,NaN,3.0,3,NaN,1,2250000.0,56,5611,1412
8,8,20251252,12,2025,8435970,1,1,1,60,NaN,...,1,NaN,30.0,5,NaN,1,1800000.0,78,7820,4415
9,9,20251252,12,2025,8435973,1,2,1,60,NaN,...,3,NaN,10.0,2,NaN,1,800000.0,1,145,6122
10,10,20251252,12,2025,8435974,1,1,1,60,NaN,...,11,NaN,20.0,3,NaN,1,220000.0,1,161,9211
11,11,20251252,12,2025,8435975,1,1,1,60,NaN,...,3,NaN,5.0,3,NaN,1,NaN,1,145,9213
12,12,20251252,12,2025,8435976,1,1,1,60,NaN,...,3,NaN,15.0,3,NaN,1,900000.0,1,161,9213
13,13,20251252,12,2025,8435976,1,2,1,60,NaN,...,11,NaN,15.0,3,NaN,1,760000.0,97,9700,9111
14,14,20251252,12,2025,8435977,1,1,1,60,NaN,...,14,NaN,NaN,5,NaN,1,300000.0,47,4719,5223
15,15,20251252,12,2025,8435977,1,2,1,60,NaN,...,3,NaN,5.0,5,NaN,1,400000.0,41,4111,9313
16,16,20251252,12,2025,8435978,1,2,1,60,NaN,...,3,NaN,5.0,9,NaN,1,500000.0,41,4111,9313
17,17,20251252,12,2025,8435979,1,1,1,60,NaN,...,3,NaN,15.0,5,NaN,1,450000.0,1,113,6111
18,18,20251252,12,2025,8435979,1,2,1,60,NaN,...,14,NaN,NaN,5,NaN,1,150000.0,47,4789,9520
19,19,20251252,12,2025,8435979,1,3,1,60,NaN,...,3,NaN,5.0,5,NaN,1,400000.0,56,5630,5223

(91357, 203)

<class 'pandas.DataFrame'>
RangeIndex: 91357 entries, 0 to 91356
Columns: 203 entries, Unnamed: 0 to OFICIO_C8
dtypes: float64(150), int64(41), str(12)
memory usage: 141.5 MB

None

,Unnamed: 0,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,...,P514,P515,P1881,P1882,P7240,OCI,INGLABO,RAMA2D_R4,RAMA4D_R4,OFICIO_C8
count,91357.000000,9.135700e+04,91357.000000,91357.0,9.135700e+04,91357.000000,91357.000000,91357.000000,91357.0,67214.000000,...,91357.000000,91357.000000,91357.000000,78336.000000,91357.000000,91357.0,8.946900e+04,91357.000000,91357.000000,91357.000000
mean,15231.525411,2.025115e+07,10.986909,2025.0,8.420420e+06,1.006009,1.755596,1.006009,60.0,41.733091,...,1.265420,1.098121,8.043489,24.000843,4.339777,1.0,1.816172e+06,53.429732,5370.550500,5899.617172
std,8800.929123,8.473843e+01,0.813127,0.0,2.847279e+04,0.091311,1.066010,0.091311,0.0,27.219270,...,0.441559,0.297479,4.504686,24.333218,2.525959,0.0,2.257874e+06,27.870947,2782.516414,2571.150336
min,0.000000,2.025104e+07,10.000000,2025.0,8.374095e+06,1.000000,1.000000,1.000000,60.0,5.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,0.000000e+00,0.000000,0.000000,0.000000
25%,7613.000000,2.025104e+07,10.000000,2025.0,8.395422e+06,1.000000,1.000000,1.000000,60.0,17.000000,...,1.000000,1.000000,3.000000,10.000000,3.000000,1.0,8.000000e+05,41.000000,4111.000000,4110.000000
50%,15226.000000,2.025115e+07,11.000000,2025.0,8.420107e+06,1.000000,1.000000,1.000000,60.0,44.000000,...,1.000000,1.000000,11.000000,20.000000,3.000000,1.0,1.423500e+06,49.000000,4921.000000,5311.000000
75%,22839.000000,2.025125e+07,12.000000,2025.0,8.442361e+06,1.000000,2.000000,1.000000,60.0,66.000000,...,2.000000,1.000000,11.000000,30.000000,8.000000,1.0,2.000000e+06,82.000000,8220.000000,8323.000000
max,30938.000000,2.025125e+07,12.000000,2025.0,8.473908e+06,5.000000,13.000000,5.000000,60.0,99.000000,...,2.000000,2.000000,15.000000,300.000000,10.000000,1.0,9.800000e+07,99.000000,9900.000000,9629.000000

In [4]:
# ANALISIS EXPLORATORIO DE OCUPADOS CON COLUMNAS RENOMBRADAS
ocupados = pd.read_csv(
    bronze_dir / config["source"]["csv_salida_ocupados"], low_memory=False
)
display(ocupados.head(20))
display(ocupados.shape)
display(ocupados.info())
display(ocupados.describe())

,Unnamed: 0,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Tipo_Registro,Area_Metropolitana,...,Medio_Transporte_Trabajo,Otro_Medio_Transporte,Minutos_Desplazamiento_Trabajo,Fuente_Recursos_Sin_Trabajo,Otra_Fuente_Recursos_Sin_Trabajo,Indicador_Ocupado,Ingreso_Laboral,Rama_Act_Empleo_Ppal,Rama_Act_Empleo_Ppal_4_Digitos,Oficio_Clasificado
0,0,20251252,12,2025,8435963,1,1,1,60,NaN,...,9,NaN,5.0,8,NaN,1,1200000.0,3,311,6223
1,1,20251252,12,2025,8435963,1,2,1,60,NaN,...,11,NaN,20.0,3,NaN,1,NaN,56,5611,9412
2,2,20251252,12,2025,8435964,1,1,1,60,NaN,...,9,NaN,30.0,3,NaN,1,2000000.0,3,311,6222
3,3,20251252,12,2025,8435965,1,1,1,60,NaN,...,9,NaN,25.0,3,NaN,1,1800000.0,3,311,6222
4,4,20251252,12,2025,8435966,1,1,1,60,NaN,...,9,NaN,20.0,3,NaN,1,2400000.0,3,311,6222
5,5,20251252,12,2025,8435967,1,1,1,60,NaN,...,9,NaN,30.0,9,NaN,1,1500000.0,3,311,6223
6,6,20251252,12,2025,8435968,1,1,1,60,NaN,...,9,NaN,25.0,3,NaN,1,1650000.0,3,311,6222
7,7,20251252,12,2025,8435969,1,1,1,60,NaN,...,3,NaN,3.0,3,NaN,1,2250000.0,56,5611,1412
8,8,20251252,12,2025,8435970,1,1,1,60,NaN,...,1,NaN,30.0,5,NaN,1,1800000.0,78,7820,4415
9,9,20251252,12,2025,8435973,1,2,1,60,NaN,...,3,NaN,10.0,2,NaN,1,800000.0,1,145,6122
10,10,20251252,12,2025,8435974,1,1,1,60,NaN,...,11,NaN,20.0,3,NaN,1,220000.0,1,161,9211
11,11,20251252,12,2025,8435975,1,1,1,60,NaN,...,3,NaN,5.0,3,NaN,1,NaN,1,145,9213
12,12,20251252,12,2025,8435976,1,1,1,60,NaN,...,3,NaN,15.0,3,NaN,1,900000.0,1,161,9213
13,13,20251252,12,2025,8435976,1,2,1,60,NaN,...,11,NaN,15.0,3,NaN,1,760000.0,97,9700,9111
14,14,20251252,12,2025,8435977,1,1,1,60,NaN,...,14,NaN,NaN,5,NaN,1,300000.0,47,4719,5223
15,15,20251252,12,2025,8435977,1,2,1,60,NaN,...,3,NaN,5.0,5,NaN,1,400000.0,41,4111,9313
16,16,20251252,12,2025,8435978,1,2,1,60,NaN,...,3,NaN,5.0,9,NaN,1,500000.0,41,4111,9313
17,17,20251252,12,2025,8435979,1,1,1,60,NaN,...,3,NaN,15.0,5,NaN,1,450000.0,1,113,6111
18,18,20251252,12,2025,8435979,1,2,1,60,NaN,...,14,NaN,NaN,5,NaN,1,150000.0,47,4789,9520
19,19,20251252,12,2025,8435979,1,3,1,60,NaN,...,3,NaN,5.0,5,NaN,1,400000.0,56,5630,5223

(91357, 203)

<class 'pandas.DataFrame'>
RangeIndex: 91357 entries, 0 to 91356
Columns: 203 entries, Unnamed: 0 to Oficio_Clasificado
dtypes: float64(150), int64(41), str(12)
memory usage: 141.5 MB

None

,Unnamed: 0,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Tipo_Registro,Area_Metropolitana,...,Trabajo_Estable,Compatibilidad_Horario_Familia,Medio_Transporte_Trabajo,Minutos_Desplazamiento_Trabajo,Fuente_Recursos_Sin_Trabajo,Indicador_Ocupado,Ingreso_Laboral,Rama_Act_Empleo_Ppal,Rama_Act_Empleo_Ppal_4_Digitos,Oficio_Clasificado
count,91357.000000,9.135700e+04,91357.000000,91357.0,9.135700e+04,91357.000000,91357.000000,91357.000000,91357.0,67214.000000,...,91357.000000,91357.000000,91357.000000,78336.000000,91357.000000,91357.0,8.946900e+04,91357.000000,91357.000000,91357.000000
mean,15231.525411,2.025115e+07,10.986909,2025.0,8.420420e+06,1.006009,1.755596,1.006009,60.0,41.733091,...,1.265420,1.098121,8.043489,24.000843,4.339777,1.0,1.816172e+06,53.429732,5370.550500,5899.617172
std,8800.929123,8.473843e+01,0.813127,0.0,2.847279e+04,0.091311,1.066010,0.091311,0.0,27.219270,...,0.441559,0.297479,4.504686,24.333218,2.525959,0.0,2.257874e+06,27.870947,2782.516414,2571.150336
min,0.000000,2.025104e+07,10.000000,2025.0,8.374095e+06,1.000000,1.000000,1.000000,60.0,5.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,0.000000e+00,0.000000,0.000000,0.000000
25%,7613.000000,2.025104e+07,10.000000,2025.0,8.395422e+06,1.000000,1.000000,1.000000,60.0,17.000000,...,1.000000,1.000000,3.000000,10.000000,3.000000,1.0,8.000000e+05,41.000000,4111.000000,4110.000000
50%,15226.000000,2.025115e+07,11.000000,2025.0,8.420107e+06,1.000000,1.000000,1.000000,60.0,44.000000,...,1.000000,1.000000,11.000000,20.000000,3.000000,1.0,1.423500e+06,49.000000,4921.000000,5311.000000
75%,22839.000000,2.025125e+07,12.000000,2025.0,8.442361e+06,1.000000,2.000000,1.000000,60.0,66.000000,...,2.000000,1.000000,11.000000,30.000000,8.000000,1.0,2.000000e+06,82.000000,8220.000000,8323.000000
max,30938.000000,2.025125e+07,12.000000,2025.0,8.473908e+06,5.000000,13.000000,5.000000,60.0,99.000000,...,2.000000,2.000000,15.000000,300.000000,10.000000,1.0,9.800000e+07,99.000000,9900.000000,9629.000000

In [5]:
# detectar nulos
print("Cantidad de nulos en caracteristicas generales")
display(caracteristicas_generales.isnull().sum())
print("Cantidad de nulos en ocupados")
display(ocupados.isnull().sum())

Cantidad de nulos en caracteristicas generales

Unnamed: 0          0
PERIODO             0
MES                 0
PER                 0
DIRECTORIO          0
SECUENCIA_P         0
ORDEN               0
HOGAR               0
REGIS               0
AREA            56034
CLASE               0
FEX_C18             0
DPTO                0
PT                  0
P6016               0
P3271               0
P6040               0
P6030S1           943
P6030S3           943
P6050               0
P6083               0
P6083S1        128068
P6081               0
P6081S1        164507
P2057               0
P2059           61925
P2061               0
P6080               0
P6080S1        194493
P6080S1A1      203851
P6070           24574
P6071          125274
P6071S1        129469
P6090               0
P6100            6212
P6110          114557
P6120          151562
P1906S1             0
P1906S2             0
P1906S3             0
P1906S4             0
P1906S5             0
P1906S6             0
P1906S7             0
P1906S8             0
P6160            5531
P6170            5531
P3041          152345
P3042            5531
P3042S1          5531
P3042S2        153351
P3043           99625
P3043S1        164403
P3038           50085
P3039           50085
POB_MAY18       50085
dtype: int64

Cantidad de nulos en ocupados

Unnamed: 0                           0
Periodo_Recoleccion                  0
Mes_Encuesta                         0
Anio_Encuesta                        0
Id_Vivienda                          0
                                  ...
Indicador_Ocupado                    0
Ingreso_Laboral                   1888
Rama_Act_Empleo_Ppal                 0
Rama_Act_Empleo_Ppal_4_Digitos       0
Oficio_Clasificado                   0
Length: 203, dtype: int64